### ISSUE TITLE
Automatically set extent on 1d and 2d histograms to the range of the dimension(s)

### ISSUE THREAD

**Issue by tarekrached** [uwdata/falcon#101]
It would be really useful to not have to specify the extent on the 1d and 2d histograms - the default could be to just set them to the range (or to some nice value encompassing the range).

**Comment by domoritz** [comment]
This could be implemented by setting the range to the extent when it's not defined. We would probably need to add a method to the database API to query the range of a dimension.

Do you want to send a PR for this?
