### ISSUE TITLE
Create application instances that interact with each other

### ISSUE THREAD

**Issue by josesaranda** [uwdata/falcon#138]
I would like to be able to create many application instances that brushes interact with each other.
In example:

An _appInstanceOne_ having two 2d charts and an _appInstanceTwo_ having one 1d chart. I want when i move brushes of the 1d chart in _appIntanceTwo_ that affect to the 2d charts in _appInstanceOne_.

How i make that possible?

**Comment by domoritz** [comment]
You would need to connect them to the same database and that might work but falcon is certainly not designed for this use case. You can read the paper about how it works. 

I'm going to close this issue since I keep the bug tracker for bugs and feature requests.

**Comment by josesaranda** [comment]
Thanks for your quick response. I'm going to try to do that.

**Comment by domoritz** [comment]
Thanks for trying out Falcon. If you have any changes, feel free to send a pull request.
