### ISSUE TITLE
 Falcon doesn't work in production mode

### ISSUE THREAD

**Issue by josesaranda** [uwdata/falcon#165]
Hi guys,

I have a project where I use Falcon to filter data from several charts. It works pretty good in development mode. However, when I try to launch the project in production mode and  I brush over a chart the other chart appear "full filtered", do you have any clue how to solved this?
Have you ever tried to launch a Falcon project in production?

Thanks in advance, you guys are doing a great job here.

![Screenshot 2019-10-07 at 17 32 05](https://user-images.githubusercontent.com/3484033/66325950-6a20aa00-e928-11e9-857a-ceee7039d518.png)

**Comment by domoritz** [comment]
Interesting. This must be a bug with parcel. I've seen things like this before and it has always been somewhat challenging to debug.

In this case, though, I can't reproduce the issue. 

```
git pull
yarn
yarn parcel build flights/index.html
cd dist
python3 -m http.server
```

Works for me. 

Can you try again or see whether there is an error message or warning somewhere?

**Comment by josesaranda** [comment]
Thanks for your quick reply.

I have reproduced the same steps to build for productions as you've described in the before sample and that's works for me. I'm having that problem when I use Falcon in a React builded project, and unfortunately there isn't any logs or warnings showing in the browser console. I only can reproduce the issue building the React project for production. And how I said Falcon works well for me in development mode.

Did you try another way to run Falcon for production? Or did you try to use Falcon in a React project before?

Please let me know if I can help you to debug this issue, and I'll be pleased to do that!

Thanks again!

**Comment by domoritz** [comment]
I have not but @tarekrached was using Falcon with React at some point.

To me, this sounds like a problem with the bundler (webpack, I assume).

**Comment by tarekrached** [comment]
It was a while ago, but IIRC create-react-app used to (before March 2019) have issues with the [arrow dependency](https://github.com/apache/arrow/tree/master/js), but it's working fine now in a vanilla create-react-build.

**Comment by josesaranda** [comment]
I have been reading the issue that you post in Parcel github's repository and i was trying to reconfigure the .terserrc file thinking that it could be the problem, but not. I'm having the same error...

I don't think the problem is Webpack bundler cause it works well in development mode. I don't know why Webpack is going to affect compiled Falcon.

Any suggestions? How can i to provide you more info about this to find the bug?

Thanks in advance! I really appreciate your effort.

**Comment by josesaranda** [comment]
Solved using latest version of Webpack without Craco and adding the next plugins for babel:
'babel-plugin-macros'
'@babel/plugin-proposal-decorators'
'babel-plugin-transform-class-properties'

Thanks for your help!
