### ISSUE TITLE
ClickHouse integration

### ISSUE THREAD

**Issue by alexey-milovidov** [uwdata/falcon#383]
[ClickHouse](https://clickhouse.tech/) is an open-source analytical DBMS:
- production grade, used by 1000s companies for the most challenging tasks [1];
- proven to have the best query processing speed (as of 2020 no other DBMS can beat ClickHouse);
- easy to install and use anywhere (baremetal, cloud, PC...)

[1] - https://clickhouse.tech/docs/en/introduction/adopters/

It looks like a natural choice to integrate with falcon.

**Comment by domoritz** [comment]
Happy to review a pull request to add clickhouse support but I won't have time to work on it. 

Similarly, duckdb would be a great target.
