### ISSUE TITLE
Generate from Vega Lite

### ISSUE THREAD

**Issue by saulshanabrook** [uwdata/falcon#75]
I am curious if I could use this library to create an interactive visualization based on the Vega Lite spec built up by the user in Altair. Do you think it would be wise/possible to generate [the App views](https://github.com/uwdata/big-crossfilter/blob/b3d9352ba751d5935bf9e86ae4b07c5ad47f1170/flights-mapd/index.ts#L26-L132) based on a vega lite schema?

Obviously, if we wanted to output directly from Altair, we would also need to create a `db`, but we could do this pretty easily based on a MapD database URL.

**Comment by domoritz** [comment]
This is anninteresting idea but I haven’t thought much about how the ideas from this library can be used in Vega and Vega-Lite. It is definitely the goal to eventually use the approach there but I feel that I am currently in the exploration phase. 

If you have any ideas or want to prototype something, I’d be happy to give you feedback.
