### ISSUE TITLE
Can't use in create-react-app applications

### ISSUE THREAD

**Issue by tarekrached** [uwdata/falcon#98]
This is due to https://github.com/apache/arrow/issues/2656

I was able to work around this by ejecting from create-react-app, and then setting `strictExportPresence` to `false` in the webpack config.

**Comment by domoritz** [comment]
Thank for noting the workaround. There isn't anything I can do so I'm closing this.

**Comment by tarekrached** [comment]
For those who come after me, the error I saw was:
```
./node_modules/@apache-arrow/es2015-esm/type.js 27:18-29
  'flatbuffers' does not contain an export named 'flatbuffers'.
```
